services:
  backend:
    env_file:
      - ./backend/.env.development

    depends_on:
      db:
        condition: service_healthy

      redis:
        condition: service_started

  db:
    image: postgres:17

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

    ports:
      - "5432:5432"

    networks:
      - my_network

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mydatabase" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  db_test:
    image: postgres:17

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdatabase

    ports:
      - "5433:5432"

    networks:
      - my_network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d testdatabase" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # frontend:
  #   build:
  #     context: ./nextjs-frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - my_network
  #   environment:
  #     - ./nextjs-frontend/.env.development
  #   volumes:
  #     - ./local-shared-data:/app/shared-data
  #   depends_on:
  #     - backend

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
