services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    env_file:
      - ./backend/.env.development

    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - WATCHFILES_FORCE_POLLING=true

    ports:
      - "8000:8000"

    networks:
      - my_network

    volumes:
      - ./backend/app:/app/app
      - ./local-shared-data:/app/shared-data

    depends_on:
      db:
        condition: service_healthy

      redis:
        condition: service_healthy

  # admin-bootstrap:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./backend/.env.development
  #   command: ["python", "-m", "commands.create_admin"]
  #   depends_on:
  #     db:
  #       condition: service_healthy

  db:
    image: postgres:17

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: artistkashi

    ports:
      - "5432:5432"

    networks:
      - my_network

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d artistkashi" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  db_test:
    image: postgres:17

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdatabase

    ports:
      - "5433:5432"

    networks:
      - my_network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d testdatabase" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # frontend:
  #   build:
  #     context: ./nextjs-frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - my_network
  #   environment:
  #     - ./nextjs-frontend/.env.development
  #   volumes:
  #     - ./local-shared-data:/app/shared-data
  #   depends_on:
  #     - backend

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
