services:
  backend:
    env_file:
      - ./backend/.env

    restart: always

    depends_on:
      redis:
        condition: service_started

  frontend:
    env_file:
      - ./nextjs-frontend/.env

    restart: always

    depends_on:
      - backend

  redis:
    restart: always