import json
import os
from pathlib import Path

from dotenv import load_dotenv

from app.main import app

load_dotenv()

OUTPUT_FILE = os.getenv("OPENAPI_OUTPUT_FILE")


def generate_openapi_schema(output_file: str) -> None:
    schema = app.openapi()

    schema = remove_operation_id_tag(schema)
    schema = normalize_error_responses(schema)

    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(schema, indent=2))

    print(f"OpenAPI schema saved to {output_file}")


def remove_operation_id_tag(schema: dict) -> dict:
    """
    Cleans up operation IDs while preventing collisions.
    Converts 'tag-name' to 'name' where possible.
    """
    seen_ids = set()
    
    for path_data in schema.get("paths", {}).values():
        for operation in path_data.values():
            if not isinstance(operation, dict):
                continue

            operation_id = operation.get("operationId")
            if not operation_id:
                continue

            # Remove tags prefix if present (e.g. 'auth-login' -> 'login')
            if "-" in operation_id:
                parts = operation_id.split("-")
                new_id = parts[-1]
                
                # If name alone is not unique, use full snake_case version
                if new_id in seen_ids:
                    new_id = operation_id.replace("-", "_")
                
                operation["operationId"] = new_id
                seen_ids.add(new_id)
            else:
                seen_ids.add(operation_id)

    return schema


def normalize_error_responses(schema: dict) -> dict:
    """
    Force all error responses to use the same ErrorResponse schema
    WITHOUT overwriting existing schemas generated by FastAPI/Pydantic.
    """

    components = schema.setdefault("components", {})
    schemas = components.setdefault("schemas", {})

    # Ensure ErrorResponse is correctly represented in components
    if "ErrorResponse" not in schemas:
        schemas["ErrorResponse"] = {
            "type": "object",
            "properties": {
                "success": {"type": "boolean", "default": False},
                "status": {"type": "integer"},
                "message": {"type": "string"},
                "error_code": {"type": "string"},
                "errors": {
                    "anyOf": [{"type": "object"}, {"type": "array"}, {"type": "null"}]
                },
                "meta": {"$ref": "#/components/schemas/Meta"},
            },
            "required": ["success", "status", "message", "error_code"],
        }

    error_ref = {"$ref": "#/components/schemas/ErrorResponse"}

    for path_data in schema.get("paths", {}).values():
        for operation in path_data.values():
            if not isinstance(operation, dict):
                continue

            responses = operation.setdefault("responses", {})

            # Standardize common error status codes
            for code in ("400", "401", "403", "404", "409", "422", "429", "500"):
                if code in responses or code == "422": # Always add 422 for validation
                    response = responses.setdefault(code, {"description": f"Error {code}"})
                    response["content"] = {"application/json": {"schema": error_ref}}

    return schema


if __name__ == "__main__":
    if not OUTPUT_FILE:
        raise RuntimeError("OPENAPI_OUTPUT_FILE not set in env")

    generate_openapi_schema(OUTPUT_FILE)
