// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AboutSection
 */
export type AboutSection = {
    /**
     * Label
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description1
     */
    description1: string;
    /**
     * Description2
     */
    description2: string;
    /**
     * Description3
     */
    description3: string;
    /**
     * Instructorname
     */
    instructorName: string;
    /**
     * Instructorrole
     */
    instructorRole: string;
    /**
     * Image
     */
    image: string;
    /**
     * Stats
     */
    stats?: Array<AboutStat>;
};

/**
 * AboutStat
 */
export type AboutStat = {
    /**
     * Label
     */
    label: string;
    /**
     * Value
     */
    value: string;
};

/**
 * AddressCreate
 */
export type AddressCreate = {
    /**
     * Line1
     */
    line1: string;
    /**
     * Line2
     */
    line2?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Country
     */
    country?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * AddressRead
 */
export type AddressRead = {
    /**
     * Line1
     */
    line1: string;
    /**
     * Line2
     */
    line2?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Country
     */
    country?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Is Default
     */
    is_default?: boolean;
    /**
     * Id
     */
    id: number;
};

/**
 * AddressUpdate
 */
export type AddressUpdate = {
    /**
     * Line1
     */
    line1?: string | null;
    /**
     * Line2
     */
    line2?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Country
     */
    country?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Is Default
     */
    is_default?: boolean | null;
};

/**
 * BannerSection
 */
export type BannerSection = {
    /**
     * Label
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Primarybtntext
     */
    primaryBtnText: string;
    /**
     * Primarybtnlink
     */
    primaryBtnLink?: string;
    /**
     * Ghostbtntext
     */
    ghostBtnText: string;
    /**
     * Ghostbtnlink
     */
    ghostBtnLink?: string;
};

/**
 * BasicHealthData
 */
export type BasicHealthData = {
    /**
     * Status
     */
    status: string;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Version
     */
    version: string;
};

/**
 * Body_ADMIN-create_product
 */
export type BodyAdminCreateProduct = {
    payload: ProductCreateRequest;
    /**
     * Files
     */
    files?: Array<Blob | File> | null;
};

/**
 * Body_ADMIN-update_product
 */
export type BodyAdminUpdateProduct = {
    payload: ProductUpdateRequest;
    /**
     * Files
     */
    files?: Array<Blob | File> | null;
};

/**
 * Body_auth-login
 */
export type BodyAuthLogin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CartItemCreate
 */
export type CartItemCreate = {
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Course Id
     */
    course_id?: number | null;
    /**
     * Quantity
     */
    quantity?: number;
};

/**
 * CartItemRead
 */
export type CartItemRead = {
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Course Id
     */
    course_id?: number | null;
    /**
     * Quantity
     */
    quantity?: number;
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: string;
    product?: ProductCardRead | null;
    course?: CourseRead | null;
};

/**
 * CartItemUpdate
 */
export type CartItemUpdate = {
    /**
     * Quantity
     */
    quantity: number;
};

/**
 * ChangePasswordRequest
 */
export type ChangePasswordRequest = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * CommunitySection
 */
export type CommunitySection = {
    /**
     * Label
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Items
     */
    items?: Array<TestimonialItem>;
};

/**
 * CourseRead
 */
export type CourseRead = {
    /**
     * Title
     */
    title: string;
    /**
     * Subtitle
     */
    subtitle?: string | null;
    /**
     * Instructor
     */
    instructor: string;
    /**
     * Level
     */
    level?: string | null;
    /**
     * Duration
     */
    duration?: string | null;
    /**
     * Lessons Count
     */
    lessons_count?: number;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Price
     */
    price: number;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Rating
     */
    rating: number;
    /**
     * Students Count
     */
    students_count: number;
    /**
     * Featured
     */
    featured: boolean;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * DetailedHealthData
 */
export type DetailedHealthData = {
    /**
     * Status
     */
    status: string;
    /**
     * Timestamp
     */
    timestamp: string;
    services: HealthServices;
};

/**
 * DimensionUnit
 */
export type DimensionUnit = 'cm' | 'inch' | 'mm';

/**
 * FaqItem
 */
export type FaqItem = {
    /**
     * Question
     */
    question: string;
    /**
     * Answer
     */
    answer: string;
};

/**
 * FaqSection
 */
export type FaqSection = {
    /**
     * Label
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Items
     */
    items?: Array<FaqItem>;
};

/**
 * FeaturedSection
 */
export type FeaturedSection = {
    /**
     * Label
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Items
     *
     * IDs of featured entities
     */
    items?: Array<number>;
};

/**
 * ForgotPasswordRequest
 */
export type ForgotPasswordRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthServices
 */
export type HealthServices = {
    database: ServiceHealth;
    redis: ServiceHealth;
};

/**
 * HeroSection
 */
export type HeroSection = {
    /**
     * Title
     */
    title: string;
    /**
     * Subtitle
     */
    subtitle: string;
    /**
     * Primarybtntext
     */
    primaryBtnText: string;
    /**
     * Primarybtnlink
     */
    primaryBtnLink?: string;
    /**
     * Ghostbtntext
     */
    ghostBtnText: string;
    /**
     * Ghostbtnlink
     */
    ghostBtnLink?: string;
    /**
     * Mediatype
     */
    mediaType?: 'image' | 'video';
    /**
     * Mediaurl
     */
    mediaUrl: string;
    /**
     * Stats
     */
    stats?: Array<HeroStat>;
};

/**
 * HeroStat
 */
export type HeroStat = {
    /**
     * Label
     */
    label: string;
    /**
     * Value
     */
    value: string;
};

/**
 * HomePageConfig
 */
export type HomePageConfig = {
    hero: HeroSection;
    featuredPaintings: FeaturedSection;
    featuredCourses: FeaturedSection;
    collection: FeaturedSection;
    bestSellers: FeaturedSection;
    about: AboutSection;
    videoCta: VideoCtaSection;
    faq: FaqSection;
    community: CommunitySection;
    banner: BannerSection;
};

/**
 * ImageSourceType
 */
export type ImageSourceType = 'upload' | 'external_url';

/**
 * LogoutRequest
 */
export type LogoutRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * Meta
 */
export type Meta = {
    /**
     * Timestamp
     */
    timestamp?: string;
    /**
     * Request Id
     */
    request_id?: string | null;
};

/**
 * PaginatedResponse[AddressRead]
 */
export type PaginatedResponseAddressRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<AddressRead>;
    pagination: Pagination;
    meta?: Meta;
};

/**
 * PaginatedResponse[CourseRead]
 */
export type PaginatedResponseCourseRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<CourseRead>;
    pagination: Pagination;
    meta?: Meta;
};

/**
 * PaginatedResponse[ProductCardRead]
 */
export type PaginatedResponseProductCardRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ProductCardRead>;
    pagination: Pagination;
    meta?: Meta;
};

/**
 * PaginatedResponse[ProductCategoryRead]
 */
export type PaginatedResponseProductCategoryRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ProductCategoryRead>;
    pagination: Pagination;
    meta?: Meta;
};

/**
 * PaginatedResponse[ProductMediumRead]
 */
export type PaginatedResponseProductMediumRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ProductMediumRead>;
    pagination: Pagination;
    meta?: Meta;
};

/**
 * PaginatedResponse[PublicUserRead]
 */
export type PaginatedResponsePublicUserRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<PublicUserRead>;
    pagination: Pagination;
    meta?: Meta;
};

/**
 * PaginatedResponse[ReviewRead]
 */
export type PaginatedResponseReviewRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ReviewRead>;
    pagination: Pagination;
    meta?: Meta;
};

/**
 * PaginatedResponse[VariantTypeRead]
 */
export type PaginatedResponseVariantTypeRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<VariantTypeRead>;
    pagination: Pagination;
    meta?: Meta;
};

/**
 * Pagination
 */
export type Pagination = {
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Items
     */
    total_items: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Has Next
     */
    has_next: boolean;
    /**
     * Has Prev
     */
    has_prev: boolean;
};

/**
 * ProductBase
 */
export type ProductBase = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Short Description
     */
    short_description?: string | null;
    /**
     * Is Original Available
     */
    is_original_available?: boolean;
    medium?: ProductMediumRead | null;
    category?: ProductCategoryRead | null;
    /**
     * Is Sold
     */
    readonly is_sold: boolean;
};

/**
 * ProductCardRead
 */
export type ProductCardRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Short Description
     */
    short_description?: string | null;
    /**
     * Is Original Available
     */
    is_original_available?: boolean;
    medium?: ProductMediumRead | null;
    category?: ProductCategoryRead | null;
    /**
     * Price
     */
    price?: string;
    /**
     * Primary Image
     */
    primary_image?: string | null;
    /**
     * Is Sold
     */
    readonly is_sold: boolean;
};

/**
 * ProductCategoryCreate
 */
export type ProductCategoryCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * ProductCategoryRead
 */
export type ProductCategoryRead = {
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * ProductCategoryUpdate
 */
export type ProductCategoryUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * ProductCreate
 */
export type ProductCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Medium Id
     */
    medium_id?: number | null;
    /**
     * Short Description
     */
    short_description?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Style
     */
    style?: string | null;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Year Created
     */
    year_created?: number | null;
    /**
     * Is Original Available
     */
    is_original_available?: boolean;
    /**
     * Is Framed
     */
    is_framed?: boolean;
    /**
     * Certificate Of Authenticity
     */
    certificate_of_authenticity?: boolean;
    /**
     * Category Id
     */
    category_id?: number | null;
    /**
     * Weight Grams
     */
    weight_grams?: number | null;
    /**
     * Is Featured
     */
    is_featured?: boolean;
    /**
     * Sort Order
     */
    sort_order?: number;
    status?: ProductStatus;
    /**
     * Meta Title
     */
    meta_title?: string | null;
    /**
     * Meta Description
     */
    meta_description?: string | null;
};

/**
 * ProductCreateRequest
 */
export type ProductCreateRequest = {
    product: ProductCreate;
    /**
     * Variants
     */
    variants?: Array<ProductVariantCreate>;
    /**
     * External Images
     */
    external_images?: Array<ProductImageInput>;
};

/**
 * ProductDetailRead
 */
export type ProductDetailRead = {
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Images
     */
    images?: Array<ProductImageRead>;
    /**
     * Variants
     */
    variants?: Array<ProductVariantRead>;
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Short Description
     */
    short_description?: string | null;
    /**
     * Is Original Available
     */
    is_original_available: boolean;
    medium?: ProductMediumRead | null;
    category?: ProductCategoryRead | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Style
     */
    style?: string | null;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Year Created
     */
    year_created?: number | null;
    /**
     * Is Framed
     */
    is_framed: boolean;
    /**
     * Certificate Of Authenticity
     */
    certificate_of_authenticity: boolean;
    /**
     * Weight Grams
     */
    weight_grams?: number | null;
    status: ProductStatus;
    /**
     * Is Featured
     */
    is_featured: boolean;
    /**
     * Sort Order
     */
    sort_order: number;
    /**
     * Meta Title
     */
    meta_title?: string | null;
    /**
     * Meta Description
     */
    meta_description?: string | null;
    /**
     * Price
     *
     * Returns the price of the default variant.
     * Falls back to the cheapest available variant if none is marked default.
     * Returns None if the product has no variants at all.
     */
    readonly price: string | null;
    /**
     * Primary Image
     *
     * Returns the URL of the image marked is_primary.
     * Falls back to the first image if none is marked primary.
     * Returns None if the product has no images.
     */
    readonly primary_image: string | null;
    /**
     * Is Sold
     */
    readonly is_sold: boolean;
};

/**
 * ProductImageInput
 *
 * Represents one external image URL submitted in the product form.
 * Uploaded files are handled separately as multipart file fields
 * and never go through this schema.
 */
export type ProductImageInput = {
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Alt Text
     */
    alt_text?: string | null;
    /**
     * Is Primary
     */
    is_primary?: boolean;
    /**
     * Sort Order
     */
    sort_order?: number;
};

/**
 * ProductImageRead
 */
export type ProductImageRead = {
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Product Id
     */
    product_id: number;
    /**
     * Image Url
     */
    image_url: string;
    /**
     * Alt Text
     */
    alt_text: string | null;
    /**
     * Is Primary
     */
    is_primary: boolean;
    /**
     * Sort Order
     */
    sort_order: number;
    source_type: ImageSourceType;
};

/**
 * ProductMediumCreate
 */
export type ProductMediumCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * ProductMediumRead
 */
export type ProductMediumRead = {
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * ProductMediumUpdate
 */
export type ProductMediumUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * ProductStatus
 */
export type ProductStatus = 'draft' | 'published' | 'sold_out' | 'archived';

/**
 * ProductUpdate
 */
export type ProductUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Medium Id
     */
    medium_id?: number | null;
    /**
     * Short Description
     */
    short_description?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Style
     */
    style?: string | null;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Year Created
     */
    year_created?: number | null;
    /**
     * Is Original Available
     */
    is_original_available?: boolean | null;
    /**
     * Is Framed
     */
    is_framed?: boolean | null;
    /**
     * Certificate Of Authenticity
     */
    certificate_of_authenticity?: boolean | null;
    /**
     * Category Id
     */
    category_id?: number | null;
    /**
     * Weight Grams
     */
    weight_grams?: number | null;
    /**
     * Is Featured
     */
    is_featured?: boolean | null;
    /**
     * Sort Order
     */
    sort_order?: number | null;
    status?: ProductStatus | null;
    /**
     * Meta Title
     */
    meta_title?: string | null;
    /**
     * Meta Description
     */
    meta_description?: string | null;
};

/**
 * ProductUpdateRequest
 */
export type ProductUpdateRequest = {
    product: ProductUpdate;
    /**
     * Variants
     */
    variants?: Array<ProductVariantUpdate>;
    /**
     * External Images
     */
    external_images?: Array<ProductImageInput>;
    /**
     * Deleted Variant Ids
     */
    deleted_variant_ids?: Array<number>;
    /**
     * Deleted Image Ids
     */
    deleted_image_ids?: Array<number>;
};

/**
 * ProductVariantCreate
 */
export type ProductVariantCreate = {
    /**
     * Variant Type Id
     */
    variant_type_id: number;
    /**
     * Width
     */
    width?: number | string | null;
    /**
     * Height
     */
    height?: number | string | null;
    dimension_unit?: DimensionUnit | null;
    /**
     * Sku
     */
    sku?: string | null;
    /**
     * Price
     */
    price: number | string;
    /**
     * Stock Quantity
     */
    stock_quantity?: number;
    /**
     * Is Default
     */
    is_default?: boolean;
    /**
     * Is Available
     */
    is_available?: boolean;
};

/**
 * ProductVariantRead
 */
export type ProductVariantRead = {
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Product Id
     */
    product_id: number;
    /**
     * Variant Type Id
     */
    variant_type_id: number | null;
    /**
     * Variant Type Name
     */
    variant_type_name?: string | null;
    /**
     * Width
     */
    width: string | null;
    /**
     * Height
     */
    height: string | null;
    dimension_unit: DimensionUnit;
    /**
     * Sku
     */
    sku: string | null;
    /**
     * Price
     */
    price: string;
    /**
     * Stock Quantity
     */
    stock_quantity: number;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Is Available
     */
    is_available: boolean;
    /**
     * Dimensions
     */
    readonly dimensions: string | null;
};

/**
 * ProductVariantUpdate
 */
export type ProductVariantUpdate = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Variant Type Id
     */
    variant_type_id?: number | null;
    /**
     * Width
     */
    width?: number | string | null;
    /**
     * Height
     */
    height?: number | string | null;
    dimension_unit?: DimensionUnit | null;
    /**
     * Sku
     */
    sku?: string | null;
    /**
     * Price
     */
    price?: number | string | null;
    /**
     * Stock Quantity
     */
    stock_quantity?: number | null;
    /**
     * Is Default
     */
    is_default?: boolean | null;
    /**
     * Is Available
     */
    is_available?: boolean | null;
};

/**
 * PublicUserRead
 */
export type PublicUserRead = {
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id?: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Profile Picture
     */
    profile_picture?: string | null;
};

/**
 * RefreshTokenRequest
 */
export type RefreshTokenRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * RequestVerificationRequest
 */
export type RequestVerificationRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * ResetPasswordRequest
 */
export type ResetPasswordRequest = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ReviewCreate
 */
export type ReviewCreate = {
    type: ReviewType;
    /**
     * Entity Id
     */
    entity_id?: number | null;
    /**
     * Rating
     */
    rating: number;
    /**
     * Text
     */
    text: string;
};

/**
 * ReviewRead
 */
export type ReviewRead = {
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    type: ReviewType;
    /**
     * Entity Id
     */
    entity_id?: number | null;
    /**
     * Rating
     */
    rating: number;
    /**
     * Text
     */
    text: string;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    status: ReviewStatus;
};

/**
 * ReviewReadPublic
 *
 * Public version without sensitive info
 */
export type ReviewReadPublic = {
    type: ReviewType;
    /**
     * Entity Id
     */
    entity_id?: number | null;
    /**
     * Rating
     */
    rating: number;
    /**
     * Text
     */
    text: string;
    /**
     * Id
     */
    id: string;
    status: ReviewStatus;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ReviewStatus
 */
export type ReviewStatus = 'active' | 'blocked';

/**
 * ReviewType
 */
export type ReviewType = 'course' | 'product';

/**
 * ReviewUpdate
 */
export type ReviewUpdate = {
    status?: ReviewStatus | null;
    /**
     * Rating
     */
    rating?: number | null;
    /**
     * Text
     */
    text?: string | null;
};

/**
 * Role
 */
export type Role = 'user' | 'admin';

/**
 * ServiceHealth
 */
export type ServiceHealth = {
    /**
     * Status
     */
    status: string;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * SuccessResponse[AddressRead]
 */
export type SuccessResponseAddressRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: AddressRead | null;
    meta?: Meta;
};

/**
 * SuccessResponse[BasicHealthData]
 */
export type SuccessResponseBasicHealthData = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: BasicHealthData | null;
    meta?: Meta;
};

/**
 * SuccessResponse[CartItemRead]
 */
export type SuccessResponseCartItemRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: CartItemRead | null;
    meta?: Meta;
};

/**
 * SuccessResponse[CourseRead]
 */
export type SuccessResponseCourseRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: CourseRead | null;
    meta?: Meta;
};

/**
 * SuccessResponse[DetailedHealthData]
 */
export type SuccessResponseDetailedHealthData = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: DetailedHealthData | null;
    meta?: Meta;
};

/**
 * SuccessResponse[HomePageConfig]
 */
export type SuccessResponseHomePageConfig = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: HomePageConfig | null;
    meta?: Meta;
};

/**
 * SuccessResponse[NoneType]
 */
export type SuccessResponseNoneType = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: null;
    meta?: Meta;
};

/**
 * SuccessResponse[ProductBase]
 */
export type SuccessResponseProductBase = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: ProductBase | null;
    meta?: Meta;
};

/**
 * SuccessResponse[ProductCategoryRead]
 */
export type SuccessResponseProductCategoryRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: ProductCategoryRead | null;
    meta?: Meta;
};

/**
 * SuccessResponse[ProductDetailRead]
 */
export type SuccessResponseProductDetailRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: ProductDetailRead | null;
    meta?: Meta;
};

/**
 * SuccessResponse[ProductImageRead]
 */
export type SuccessResponseProductImageRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: ProductImageRead | null;
    meta?: Meta;
};

/**
 * SuccessResponse[ProductMediumRead]
 */
export type SuccessResponseProductMediumRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: ProductMediumRead | null;
    meta?: Meta;
};

/**
 * SuccessResponse[ProductVariantRead]
 */
export type SuccessResponseProductVariantRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: ProductVariantRead | null;
    meta?: Meta;
};

/**
 * SuccessResponse[ReviewRead]
 */
export type SuccessResponseReviewRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: ReviewRead | null;
    meta?: Meta;
};

/**
 * SuccessResponse[TokenResponse]
 */
export type SuccessResponseTokenResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: TokenResponse | null;
    meta?: Meta;
};

/**
 * SuccessResponse[UserProfileRead]
 */
export type SuccessResponseUserProfileRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: UserProfileRead | null;
    meta?: Meta;
};

/**
 * SuccessResponse[UserRead]
 */
export type SuccessResponseUserRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: UserRead | null;
    meta?: Meta;
};

/**
 * SuccessResponse[VariantTypeRead]
 */
export type SuccessResponseVariantTypeRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: VariantTypeRead | null;
    meta?: Meta;
};

/**
 * SuccessResponse[WishlistRead]
 */
export type SuccessResponseWishlistRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: WishlistRead | null;
    meta?: Meta;
};

/**
 * SuccessResponse[dict]
 */
export type SuccessResponseDict = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    } | null;
    meta?: Meta;
};

/**
 * SuccessResponse[dict[str, int]]
 */
export type SuccessResponseDictStrInt = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: {
        [key: string]: number;
    } | null;
    meta?: Meta;
};

/**
 * SuccessResponse[dict[str, str]]
 */
export type SuccessResponseDictStrStr = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: {
        [key: string]: string;
    } | null;
    meta?: Meta;
};

/**
 * SuccessResponse[list[AddressRead]]
 */
export type SuccessResponseListAddressRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<AddressRead> | null;
    meta?: Meta;
};

/**
 * SuccessResponse[list[CartItemRead]]
 */
export type SuccessResponseListCartItemRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<CartItemRead> | null;
    meta?: Meta;
};

/**
 * SuccessResponse[list[ProductImageRead]]
 */
export type SuccessResponseListProductImageRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ProductImageRead> | null;
    meta?: Meta;
};

/**
 * SuccessResponse[list[ProductVariantRead]]
 */
export type SuccessResponseListProductVariantRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ProductVariantRead> | null;
    meta?: Meta;
};

/**
 * SuccessResponse[list[ReviewReadPublic]]
 */
export type SuccessResponseListReviewReadPublic = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ReviewReadPublic> | null;
    meta?: Meta;
};

/**
 * SuccessResponse[list[ReviewRead]]
 */
export type SuccessResponseListReviewRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ReviewRead> | null;
    meta?: Meta;
};

/**
 * SuccessResponse[list[WishlistRead]]
 */
export type SuccessResponseListWishlistRead = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<WishlistRead> | null;
    meta?: Meta;
};

/**
 * SuccessResponse[list[dict]]
 */
export type SuccessResponseListDict = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<{
        [key: string]: unknown;
    }> | null;
    meta?: Meta;
};

/**
 * SuccessResponse[list[dict[str, str]]]
 */
export type SuccessResponseListDictStrStr = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<{
        [key: string]: string;
    }> | null;
    meta?: Meta;
};

/**
 * TestimonialItem
 */
export type TestimonialItem = {
    /**
     * Name
     */
    name: string;
    /**
     * Role
     */
    role: string;
    /**
     * Text
     */
    text: string;
    /**
     * Rating
     */
    rating?: number;
    /**
     * Avatar
     */
    avatar: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Phone
     */
    phone?: string | null;
};

/**
 * UserProfileRead
 */
export type UserProfileRead = {
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id?: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Profile Picture
     */
    profile_picture?: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Verified
     */
    is_verified: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    role: Role;
    /**
     * Addresses
     */
    addresses?: Array<AddressRead>;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id?: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Profile Picture
     */
    profile_picture?: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Verified
     */
    is_verified: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    role: Role;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VariantTypeCreate
 */
export type VariantTypeCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * VariantTypeRead
 */
export type VariantTypeRead = {
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * VariantTypeUpdate
 */
export type VariantTypeUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * VerifyEmailRequest
 */
export type VerifyEmailRequest = {
    /**
     * Token
     */
    token: string;
};

/**
 * VideoCtaSection
 */
export type VideoCtaSection = {
    /**
     * Label
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Bgimage
     */
    bgImage: string;
    /**
     * Videourl
     */
    videoUrl: string;
};

/**
 * WishlistCreate
 */
export type WishlistCreate = {
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Course Id
     */
    course_id?: number | null;
};

/**
 * WishlistRead
 */
export type WishlistRead = {
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Course Id
     */
    course_id?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: string;
    product?: ProductCardRead | null;
    course?: CourseRead | null;
};

export type ErrorResponse = {
    success: boolean;
    status: number;
    message: string;
    error_code: string;
    errors?: {
        [key: string]: unknown;
    } | Array<unknown> | null;
    meta?: Meta;
};

/**
 * CartItemRead
 */
export type CartItemReadWritable = {
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Course Id
     */
    course_id?: number | null;
    /**
     * Quantity
     */
    quantity?: number;
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: string;
    product?: ProductCardReadWritable | null;
    course?: CourseRead | null;
};

/**
 * PaginatedResponse[ProductCardRead]
 */
export type PaginatedResponseProductCardReadWritable = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ProductCardReadWritable>;
    pagination: Pagination;
    meta?: Meta;
};

/**
 * ProductBase
 */
export type ProductBaseWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Short Description
     */
    short_description?: string | null;
    /**
     * Is Original Available
     */
    is_original_available?: boolean;
    medium?: ProductMediumRead | null;
    category?: ProductCategoryRead | null;
};

/**
 * ProductCardRead
 */
export type ProductCardReadWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Short Description
     */
    short_description?: string | null;
    /**
     * Is Original Available
     */
    is_original_available?: boolean;
    medium?: ProductMediumRead | null;
    category?: ProductCategoryRead | null;
    /**
     * Price
     */
    price?: string;
    /**
     * Primary Image
     */
    primary_image?: string | null;
};

/**
 * ProductDetailRead
 */
export type ProductDetailReadWritable = {
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Images
     */
    images?: Array<ProductImageRead>;
    /**
     * Variants
     */
    variants?: Array<ProductVariantReadWritable>;
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Short Description
     */
    short_description?: string | null;
    /**
     * Is Original Available
     */
    is_original_available: boolean;
    medium?: ProductMediumRead | null;
    category?: ProductCategoryRead | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Style
     */
    style?: string | null;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Year Created
     */
    year_created?: number | null;
    /**
     * Is Framed
     */
    is_framed: boolean;
    /**
     * Certificate Of Authenticity
     */
    certificate_of_authenticity: boolean;
    /**
     * Weight Grams
     */
    weight_grams?: number | null;
    status: ProductStatus;
    /**
     * Is Featured
     */
    is_featured: boolean;
    /**
     * Sort Order
     */
    sort_order: number;
    /**
     * Meta Title
     */
    meta_title?: string | null;
    /**
     * Meta Description
     */
    meta_description?: string | null;
};

/**
 * ProductVariantRead
 */
export type ProductVariantReadWritable = {
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Product Id
     */
    product_id: number;
    /**
     * Variant Type Id
     */
    variant_type_id: number | null;
    /**
     * Variant Type Name
     */
    variant_type_name?: string | null;
    /**
     * Width
     */
    width: string | null;
    /**
     * Height
     */
    height: string | null;
    dimension_unit: DimensionUnit;
    /**
     * Sku
     */
    sku: string | null;
    /**
     * Price
     */
    price: string;
    /**
     * Stock Quantity
     */
    stock_quantity: number;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Is Available
     */
    is_available: boolean;
};

/**
 * SuccessResponse[CartItemRead]
 */
export type SuccessResponseCartItemReadWritable = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: CartItemReadWritable | null;
    meta?: Meta;
};

/**
 * SuccessResponse[ProductBase]
 */
export type SuccessResponseProductBaseWritable = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: ProductBaseWritable | null;
    meta?: Meta;
};

/**
 * SuccessResponse[ProductDetailRead]
 */
export type SuccessResponseProductDetailReadWritable = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: ProductDetailReadWritable | null;
    meta?: Meta;
};

/**
 * SuccessResponse[ProductVariantRead]
 */
export type SuccessResponseProductVariantReadWritable = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: ProductVariantReadWritable | null;
    meta?: Meta;
};

/**
 * SuccessResponse[WishlistRead]
 */
export type SuccessResponseWishlistReadWritable = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    data?: WishlistReadWritable | null;
    meta?: Meta;
};

/**
 * SuccessResponse[list[CartItemRead]]
 */
export type SuccessResponseListCartItemReadWritable = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<CartItemReadWritable> | null;
    meta?: Meta;
};

/**
 * SuccessResponse[list[ProductVariantRead]]
 */
export type SuccessResponseListProductVariantReadWritable = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ProductVariantReadWritable> | null;
    meta?: Meta;
};

/**
 * SuccessResponse[list[WishlistRead]]
 */
export type SuccessResponseListWishlistReadWritable = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Status
     */
    status?: number;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<WishlistReadWritable> | null;
    meta?: Meta;
};

/**
 * WishlistRead
 */
export type WishlistReadWritable = {
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Course Id
     */
    course_id?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: string;
    product?: ProductCardReadWritable | null;
    course?: CourseRead | null;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors];

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseBasicHealthData;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type HealthCheckDetailedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/detailed';
};

export type HealthCheckDetailedErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type HealthCheckDetailedError = HealthCheckDetailedErrors[keyof HealthCheckDetailedErrors];

export type HealthCheckDetailedResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseDetailedHealthData;
};

export type HealthCheckDetailedResponse = HealthCheckDetailedResponses[keyof HealthCheckDetailedResponses];

export type AdminStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/stats';
};

export type AdminStatsErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type AdminStatsError = AdminStatsErrors[keyof AdminStatsErrors];

export type AdminStatsResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseDictStrInt;
};

export type AdminStatsResponse = AdminStatsResponses[keyof AdminStatsResponses];

export type GetHomePageSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/config/home';
};

export type GetHomePageSettingsErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type GetHomePageSettingsError = GetHomePageSettingsErrors[keyof GetHomePageSettingsErrors];

export type GetHomePageSettingsResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseHomePageConfig;
};

export type GetHomePageSettingsResponse = GetHomePageSettingsResponses[keyof GetHomePageSettingsResponses];

export type UpdateHomePageSettingsData = {
    body: HomePageConfig;
    path?: never;
    query?: never;
    url: '/api/admin/config/home';
};

export type UpdateHomePageSettingsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateHomePageSettingsError = UpdateHomePageSettingsErrors[keyof UpdateHomePageSettingsErrors];

export type UpdateHomePageSettingsResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseHomePageConfig;
};

export type UpdateHomePageSettingsResponse = UpdateHomePageSettingsResponses[keyof UpdateHomePageSettingsResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/users';
};

export type ListUsersErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseListDict;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/admin/users/{user_id}';
};

export type GetUserErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseDict;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type ListCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/admin/product-categories';
};

export type ListCategoriesErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ListCategoriesError = ListCategoriesErrors[keyof ListCategoriesErrors];

export type ListCategoriesResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseProductCategoryRead;
};

export type ListCategoriesResponse = ListCategoriesResponses[keyof ListCategoriesResponses];

export type CreateCategoryData = {
    body: ProductCategoryCreate;
    path?: never;
    query?: never;
    url: '/api/admin/product-categories';
};

export type CreateCategoryErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreateCategoryError = CreateCategoryErrors[keyof CreateCategoryErrors];

export type CreateCategoryResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductCategoryRead;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        /**
         * Category Id
         */
        category_id: number;
    };
    query?: never;
    url: '/api/admin/product-categories/{category_id}';
};

export type DeleteCategoryErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type DeleteCategoryError = DeleteCategoryErrors[keyof DeleteCategoryErrors];

export type DeleteCategoryResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type DeleteCategoryResponse = DeleteCategoryResponses[keyof DeleteCategoryResponses];

export type GetCategoryData = {
    body?: never;
    path: {
        /**
         * Category Id
         */
        category_id: number;
    };
    query?: never;
    url: '/api/admin/product-categories/{category_id}';
};

export type GetCategoryErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetCategoryError = GetCategoryErrors[keyof GetCategoryErrors];

export type GetCategoryResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductCategoryRead;
};

export type GetCategoryResponse = GetCategoryResponses[keyof GetCategoryResponses];

export type UpdateCategoryData = {
    body: ProductCategoryUpdate;
    path: {
        /**
         * Category Id
         */
        category_id: number;
    };
    query?: never;
    url: '/api/admin/product-categories/{category_id}';
};

export type UpdateCategoryErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateCategoryError = UpdateCategoryErrors[keyof UpdateCategoryErrors];

export type UpdateCategoryResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductCategoryRead;
};

export type UpdateCategoryResponse = UpdateCategoryResponses[keyof UpdateCategoryResponses];

export type ListMediumsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/admin/product-mediums';
};

export type ListMediumsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ListMediumsError = ListMediumsErrors[keyof ListMediumsErrors];

export type ListMediumsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseProductMediumRead;
};

export type ListMediumsResponse = ListMediumsResponses[keyof ListMediumsResponses];

export type CreateMediumData = {
    body: ProductMediumCreate;
    path?: never;
    query?: never;
    url: '/api/admin/product-mediums';
};

export type CreateMediumErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreateMediumError = CreateMediumErrors[keyof CreateMediumErrors];

export type CreateMediumResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductMediumRead;
};

export type CreateMediumResponse = CreateMediumResponses[keyof CreateMediumResponses];

export type DeleteMediumData = {
    body?: never;
    path: {
        /**
         * Medium Id
         */
        medium_id: number;
    };
    query?: never;
    url: '/api/admin/product-mediums/{medium_id}';
};

export type DeleteMediumErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type DeleteMediumError = DeleteMediumErrors[keyof DeleteMediumErrors];

export type DeleteMediumResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type DeleteMediumResponse = DeleteMediumResponses[keyof DeleteMediumResponses];

export type GetMediumData = {
    body?: never;
    path: {
        /**
         * Medium Id
         */
        medium_id: number;
    };
    query?: never;
    url: '/api/admin/product-mediums/{medium_id}';
};

export type GetMediumErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetMediumError = GetMediumErrors[keyof GetMediumErrors];

export type GetMediumResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductMediumRead;
};

export type GetMediumResponse = GetMediumResponses[keyof GetMediumResponses];

export type UpdateMediumData = {
    body: ProductMediumUpdate;
    path: {
        /**
         * Medium Id
         */
        medium_id: number;
    };
    query?: never;
    url: '/api/admin/product-mediums/{medium_id}';
};

export type UpdateMediumErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateMediumError = UpdateMediumErrors[keyof UpdateMediumErrors];

export type UpdateMediumResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductMediumRead;
};

export type UpdateMediumResponse = UpdateMediumResponses[keyof UpdateMediumResponses];

export type ListVariantTypesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/admin/variant-types';
};

export type ListVariantTypesErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ListVariantTypesError = ListVariantTypesErrors[keyof ListVariantTypesErrors];

export type ListVariantTypesResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseVariantTypeRead;
};

export type ListVariantTypesResponse = ListVariantTypesResponses[keyof ListVariantTypesResponses];

export type CreateVariantTypeData = {
    body: VariantTypeCreate;
    path?: never;
    query?: never;
    url: '/api/admin/variant-types';
};

export type CreateVariantTypeErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreateVariantTypeError = CreateVariantTypeErrors[keyof CreateVariantTypeErrors];

export type CreateVariantTypeResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseVariantTypeRead;
};

export type CreateVariantTypeResponse = CreateVariantTypeResponses[keyof CreateVariantTypeResponses];

export type DeleteVariantTypeData = {
    body?: never;
    path: {
        /**
         * Variant Type Id
         */
        variant_type_id: number;
    };
    query?: never;
    url: '/api/admin/variant-types/{variant_type_id}';
};

export type DeleteVariantTypeErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type DeleteVariantTypeError = DeleteVariantTypeErrors[keyof DeleteVariantTypeErrors];

export type DeleteVariantTypeResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type DeleteVariantTypeResponse = DeleteVariantTypeResponses[keyof DeleteVariantTypeResponses];

export type GetVariantTypeData = {
    body?: never;
    path: {
        /**
         * Variant Type Id
         */
        variant_type_id: number;
    };
    query?: never;
    url: '/api/admin/variant-types/{variant_type_id}';
};

export type GetVariantTypeErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetVariantTypeError = GetVariantTypeErrors[keyof GetVariantTypeErrors];

export type GetVariantTypeResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseVariantTypeRead;
};

export type GetVariantTypeResponse = GetVariantTypeResponses[keyof GetVariantTypeResponses];

export type UpdateVariantTypeData = {
    body: VariantTypeUpdate;
    path: {
        /**
         * Variant Type Id
         */
        variant_type_id: number;
    };
    query?: never;
    url: '/api/admin/variant-types/{variant_type_id}';
};

export type UpdateVariantTypeErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateVariantTypeError = UpdateVariantTypeErrors[keyof UpdateVariantTypeErrors];

export type UpdateVariantTypeResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseVariantTypeRead;
};

export type UpdateVariantTypeResponse = UpdateVariantTypeResponses[keyof UpdateVariantTypeResponses];

export type ListProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Category Id
         */
        category_id?: number | null;
        /**
         * Is Featured
         */
        is_featured?: boolean | null;
    };
    url: '/api/admin/products';
};

export type ListProductsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ListProductsError = ListProductsErrors[keyof ListProductsErrors];

export type ListProductsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseProductCardRead;
};

export type ListProductsResponse = ListProductsResponses[keyof ListProductsResponses];

export type CreateProductData = {
    body: BodyAdminCreateProduct;
    path?: never;
    query?: never;
    url: '/api/admin/products';
};

export type CreateProductErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreateProductError = CreateProductErrors[keyof CreateProductErrors];

export type CreateProductResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductDetailRead;
};

export type CreateProductResponse = CreateProductResponses[keyof CreateProductResponses];

export type FeaturedProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/admin/products/featured';
};

export type FeaturedProductsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type FeaturedProductsError = FeaturedProductsErrors[keyof FeaturedProductsErrors];

export type FeaturedProductsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseProductCardRead;
};

export type FeaturedProductsResponse = FeaturedProductsResponses[keyof FeaturedProductsResponses];

export type SearchProductsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/admin/products/search';
};

export type SearchProductsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type SearchProductsError = SearchProductsErrors[keyof SearchProductsErrors];

export type SearchProductsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseProductCardRead;
};

export type SearchProductsResponse = SearchProductsResponses[keyof SearchProductsResponses];

export type GetProductBySlugData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/admin/products/slug/{slug}';
};

export type GetProductBySlugErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetProductBySlugError = GetProductBySlugErrors[keyof GetProductBySlugErrors];

export type GetProductBySlugResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductDetailRead;
};

export type GetProductBySlugResponse = GetProductBySlugResponses[keyof GetProductBySlugResponses];

export type DeleteProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/api/admin/products/{product_id}';
};

export type DeleteProductErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type DeleteProductError = DeleteProductErrors[keyof DeleteProductErrors];

export type DeleteProductResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type DeleteProductResponse = DeleteProductResponses[keyof DeleteProductResponses];

export type GetProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/api/admin/products/{product_id}';
};

export type GetProductErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetProductError = GetProductErrors[keyof GetProductErrors];

export type GetProductResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductDetailRead;
};

export type GetProductResponse = GetProductResponses[keyof GetProductResponses];

export type UpdateProductData = {
    body: BodyAdminUpdateProduct;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/api/admin/products/{product_id}';
};

export type UpdateProductErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateProductError = UpdateProductErrors[keyof UpdateProductErrors];

export type UpdateProductResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductDetailRead;
};

export type UpdateProductResponse = UpdateProductResponses[keyof UpdateProductResponses];

export type PublishProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/api/admin/products/{product_id}/publish';
};

export type PublishProductErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type PublishProductError = PublishProductErrors[keyof PublishProductErrors];

export type PublishProductResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductBase;
};

export type PublishProductResponse = PublishProductResponses[keyof PublishProductResponses];

export type ArchiveProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/api/admin/products/{product_id}/archive';
};

export type ArchiveProductErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ArchiveProductError = ArchiveProductErrors[keyof ArchiveProductErrors];

export type ArchiveProductResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductBase;
};

export type ArchiveProductResponse = ArchiveProductResponses[keyof ArchiveProductResponses];

export type GetVariantData = {
    body?: never;
    path: {
        /**
         * Variant Id
         */
        variant_id: number;
    };
    query?: never;
    url: '/api/admin/variants/{variant_id}';
};

export type GetVariantErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetVariantError = GetVariantErrors[keyof GetVariantErrors];

export type GetVariantResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductVariantRead;
};

export type GetVariantResponse = GetVariantResponses[keyof GetVariantResponses];

export type ListVariantsData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/api/admin/variants/product/{product_id}';
};

export type ListVariantsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ListVariantsError = ListVariantsErrors[keyof ListVariantsErrors];

export type ListVariantsResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseListProductVariantRead;
};

export type ListVariantsResponse = ListVariantsResponses[keyof ListVariantsResponses];

export type GetProductImagesData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/api/admin/images/product/{product_id}';
};

export type GetProductImagesErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetProductImagesError = GetProductImagesErrors[keyof GetProductImagesErrors];

export type GetProductImagesResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseListProductImageRead;
};

export type GetProductImagesResponse = GetProductImagesResponses[keyof GetProductImagesResponses];

export type GetImageData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: number;
    };
    query?: never;
    url: '/api/admin/images/{image_id}';
};

export type GetImageErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetImageError = GetImageErrors[keyof GetImageErrors];

export type GetImageResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductImageRead;
};

export type GetImageResponse = GetImageResponses[keyof GetImageResponses];

export type ListCoursesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/courses';
};

export type ListCoursesErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type ListCoursesError = ListCoursesErrors[keyof ListCoursesErrors];

export type ListCoursesResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseListDictStrStr;
};

export type ListCoursesResponse = ListCoursesResponses[keyof ListCoursesResponses];

export type GetCourseData = {
    body?: never;
    path: {
        /**
         * Course Id
         */
        course_id: string;
    };
    query?: never;
    url: '/api/admin/courses/{course_id}';
};

export type GetCourseErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetCourseError = GetCourseErrors[keyof GetCourseErrors];

export type GetCourseResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseDictStrStr;
};

export type GetCourseResponse = GetCourseResponses[keyof GetCourseResponses];

export type OverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/dashboard/overview';
};

export type OverviewErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type OverviewError = OverviewErrors[keyof OverviewErrors];

export type OverviewResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseDictStrInt;
};

export type OverviewResponse = OverviewResponses[keyof OverviewResponses];

export type ListAllReviewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Review Type
         */
        review_type?: ReviewType | null;
        /**
         * Entity Id
         */
        entity_id?: number | null;
        /**
         * Status
         */
        status?: ReviewStatus | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/admin/reviews';
};

export type ListAllReviewsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ListAllReviewsError = ListAllReviewsErrors[keyof ListAllReviewsErrors];

export type ListAllReviewsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseReviewRead;
};

export type ListAllReviewsResponse = ListAllReviewsResponses[keyof ListAllReviewsResponses];

export type DeleteReviewData = {
    body?: never;
    path: {
        /**
         * Review Id
         */
        review_id: string;
    };
    query?: never;
    url: '/api/admin/reviews/{review_id}';
};

export type DeleteReviewErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type DeleteReviewError = DeleteReviewErrors[keyof DeleteReviewErrors];

export type DeleteReviewResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseDict;
};

export type DeleteReviewResponse = DeleteReviewResponses[keyof DeleteReviewResponses];

export type GetReviewDetailData = {
    body?: never;
    path: {
        /**
         * Review Id
         */
        review_id: string;
    };
    query?: never;
    url: '/api/admin/reviews/{review_id}';
};

export type GetReviewDetailErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetReviewDetailError = GetReviewDetailErrors[keyof GetReviewDetailErrors];

export type GetReviewDetailResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseReviewRead;
};

export type GetReviewDetailResponse = GetReviewDetailResponses[keyof GetReviewDetailResponses];

export type UpdateReviewData = {
    body: ReviewUpdate;
    path: {
        /**
         * Review Id
         */
        review_id: string;
    };
    query?: never;
    url: '/api/admin/reviews/{review_id}';
};

export type UpdateReviewErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateReviewError = UpdateReviewErrors[keyof UpdateReviewErrors];

export type UpdateReviewResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseReviewRead;
};

export type UpdateReviewResponse = UpdateReviewResponses[keyof UpdateReviewResponses];

export type RegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: BodyAuthLogin;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseTokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RefreshTokenData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshTokenErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseTokenResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseUserRead;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type ForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/forgot-password';
};

export type ForgotPasswordErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ForgotPasswordError = ForgotPasswordErrors[keyof ForgotPasswordErrors];

export type ForgotPasswordResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type ForgotPasswordResponse = ForgotPasswordResponses[keyof ForgotPasswordResponses];

export type ResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/reset-password';
};

export type ResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type ChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/change-password';
};

export type ChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type RequestVerificationData = {
    body: RequestVerificationRequest;
    path?: never;
    query?: never;
    url: '/api/auth/request-verification';
};

export type RequestVerificationErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type RequestVerificationError = RequestVerificationErrors[keyof RequestVerificationErrors];

export type RequestVerificationResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type RequestVerificationResponse = RequestVerificationResponses[keyof RequestVerificationResponses];

export type VerifyEmailData = {
    body: VerifyEmailRequest;
    path?: never;
    query?: never;
    url: '/api/auth/verify';
};

export type VerifyEmailErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type VerifyEmailError = VerifyEmailErrors[keyof VerifyEmailErrors];

export type VerifyEmailResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type VerifyEmailResponse = VerifyEmailResponses[keyof VerifyEmailResponses];

export type LogoutData = {
    body: LogoutRequest;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LogoutAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout-all';
};

export type LogoutAllErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type LogoutAllError = LogoutAllErrors[keyof LogoutAllErrors];

export type LogoutAllResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type LogoutAllResponse = LogoutAllResponses[keyof LogoutAllResponses];

export type ReadOwnProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profiles/me';
};

export type ReadOwnProfileErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type ReadOwnProfileError = ReadOwnProfileErrors[keyof ReadOwnProfileErrors];

export type ReadOwnProfileResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseUserProfileRead;
};

export type ReadOwnProfileResponse = ReadOwnProfileResponses[keyof ReadOwnProfileResponses];

export type ReadMyAddressesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profiles/me/addresses';
};

export type ReadMyAddressesErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type ReadMyAddressesError = ReadMyAddressesErrors[keyof ReadMyAddressesErrors];

export type ReadMyAddressesResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseListAddressRead;
};

export type ReadMyAddressesResponse = ReadMyAddressesResponses[keyof ReadMyAddressesResponses];

export type ListProfilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/profiles';
};

export type ListProfilesErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ListProfilesError = ListProfilesErrors[keyof ListProfilesErrors];

export type ListProfilesResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponsePublicUserRead;
};

export type ListProfilesResponse = ListProfilesResponses[keyof ListProfilesResponses];

export type ListAddressesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/addresses';
};

export type ListAddressesErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ListAddressesError = ListAddressesErrors[keyof ListAddressesErrors];

export type ListAddressesResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseAddressRead;
};

export type ListAddressesResponse = ListAddressesResponses[keyof ListAddressesResponses];

export type CreateAddressData = {
    body: AddressCreate;
    path?: never;
    query?: never;
    url: '/api/addresses';
};

export type CreateAddressErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreateAddressError = CreateAddressErrors[keyof CreateAddressErrors];

export type CreateAddressResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseAddressRead;
};

export type CreateAddressResponse = CreateAddressResponses[keyof CreateAddressResponses];

export type DeleteAddressData = {
    body?: never;
    path: {
        /**
         * Address Id
         */
        address_id: number;
    };
    query?: never;
    url: '/api/addresses/{address_id}';
};

export type DeleteAddressErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type DeleteAddressError = DeleteAddressErrors[keyof DeleteAddressErrors];

export type DeleteAddressResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseDict;
};

export type DeleteAddressResponse = DeleteAddressResponses[keyof DeleteAddressResponses];

export type UpdateAddressData = {
    body: AddressUpdate;
    path: {
        /**
         * Address Id
         */
        address_id: number;
    };
    query?: never;
    url: '/api/addresses/{address_id}';
};

export type UpdateAddressErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateAddressError = UpdateAddressErrors[keyof UpdateAddressErrors];

export type UpdateAddressResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseAddressRead;
};

export type UpdateAddressResponse = UpdateAddressResponses[keyof UpdateAddressResponses];

export type ListReviewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Review Type
         */
        review_type?: ReviewType | null;
        /**
         * Entity Id
         */
        entity_id?: number | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/reviews';
};

export type ListReviewsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ListReviewsError = ListReviewsErrors[keyof ListReviewsErrors];

export type ListReviewsResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseListReviewReadPublic;
};

export type ListReviewsResponse = ListReviewsResponses[keyof ListReviewsResponses];

export type CreateReviewData = {
    body: ReviewCreate;
    path?: never;
    query?: never;
    url: '/api/reviews';
};

export type CreateReviewErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreateReviewError = CreateReviewErrors[keyof CreateReviewErrors];

export type CreateReviewResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseReviewRead;
};

export type CreateReviewResponse = CreateReviewResponses[keyof CreateReviewResponses];

export type GetMyReviewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/reviews/user/my-reviews';
};

export type GetMyReviewsErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type GetMyReviewsError = GetMyReviewsErrors[keyof GetMyReviewsErrors];

export type GetMyReviewsResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseListReviewRead;
};

export type GetMyReviewsResponse = GetMyReviewsResponses[keyof GetMyReviewsResponses];

export type CoursesListCoursesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/courses';
};

export type CoursesListCoursesErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CoursesListCoursesError = CoursesListCoursesErrors[keyof CoursesListCoursesErrors];

export type CoursesListCoursesResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseCourseRead;
};

export type CoursesListCoursesResponse = CoursesListCoursesResponses[keyof CoursesListCoursesResponses];

export type CoursesGetCourseData = {
    body?: never;
    path: {
        /**
         * Course Id
         */
        course_id: number;
    };
    query?: never;
    url: '/api/courses/{course_id}';
};

export type CoursesGetCourseErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CoursesGetCourseError = CoursesGetCourseErrors[keyof CoursesGetCourseErrors];

export type CoursesGetCourseResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseCourseRead;
};

export type CoursesGetCourseResponse = CoursesGetCourseResponses[keyof CoursesGetCourseResponses];

export type ProductsListProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/products';
};

export type ProductsListProductsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ProductsListProductsError = ProductsListProductsErrors[keyof ProductsListProductsErrors];

export type ProductsListProductsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseProductCardRead;
};

export type ProductsListProductsResponse = ProductsListProductsResponses[keyof ProductsListProductsResponses];

export type ProductsGetProductData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/products/{slug}';
};

export type ProductsGetProductErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ProductsGetProductError = ProductsGetProductErrors[keyof ProductsGetProductErrors];

export type ProductsGetProductResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseProductDetailRead;
};

export type ProductsGetProductResponse = ProductsGetProductResponses[keyof ProductsGetProductResponses];

export type GetMyCartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/cart';
};

export type GetMyCartErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type GetMyCartError = GetMyCartErrors[keyof GetMyCartErrors];

export type GetMyCartResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseListCartItemRead;
};

export type GetMyCartResponse = GetMyCartResponses[keyof GetMyCartResponses];

export type AddToCartData = {
    body: CartItemCreate;
    path?: never;
    query?: never;
    url: '/api/cart';
};

export type AddToCartErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type AddToCartError = AddToCartErrors[keyof AddToCartErrors];

export type AddToCartResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseCartItemRead;
};

export type AddToCartResponse = AddToCartResponses[keyof AddToCartResponses];

export type RemoveFromCartData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/api/cart/{item_id}';
};

export type RemoveFromCartErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type RemoveFromCartError = RemoveFromCartErrors[keyof RemoveFromCartErrors];

export type RemoveFromCartResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type RemoveFromCartResponse = RemoveFromCartResponses[keyof RemoveFromCartResponses];

export type UpdateCartItemData = {
    body: CartItemUpdate;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/api/cart/{item_id}';
};

export type UpdateCartItemErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateCartItemError = UpdateCartItemErrors[keyof UpdateCartItemErrors];

export type UpdateCartItemResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseCartItemRead;
};

export type UpdateCartItemResponse = UpdateCartItemResponses[keyof UpdateCartItemResponses];

export type GetMyWishlistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/wishlist';
};

export type GetMyWishlistErrors = {
    /**
     * Error 422
     */
    422: ErrorResponse;
};

export type GetMyWishlistError = GetMyWishlistErrors[keyof GetMyWishlistErrors];

export type GetMyWishlistResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseListWishlistRead;
};

export type GetMyWishlistResponse = GetMyWishlistResponses[keyof GetMyWishlistResponses];

export type AddToWishlistData = {
    body: WishlistCreate;
    path?: never;
    query?: never;
    url: '/api/wishlist';
};

export type AddToWishlistErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type AddToWishlistError = AddToWishlistErrors[keyof AddToWishlistErrors];

export type AddToWishlistResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseWishlistRead;
};

export type AddToWishlistResponse = AddToWishlistResponses[keyof AddToWishlistResponses];

export type RemoveFromWishlistData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/api/wishlist/{item_id}';
};

export type RemoveFromWishlistErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type RemoveFromWishlistError = RemoveFromWishlistErrors[keyof RemoveFromWishlistErrors];

export type RemoveFromWishlistResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponseNoneType;
};

export type RemoveFromWishlistResponse = RemoveFromWishlistResponses[keyof RemoveFromWishlistResponses];
