// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AboutSection
 */
export type AboutSection = {
    /**
     * Label
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description1
     */
    description1: string;
    /**
     * Description2
     */
    description2: string;
    /**
     * Description3
     */
    description3: string;
    /**
     * Instructorname
     */
    instructorName: string;
    /**
     * Instructorrole
     */
    instructorRole: string;
    /**
     * Image
     */
    image: string;
    /**
     * Stats
     */
    stats?: Array<AboutStat>;
};

/**
 * AboutStat
 */
export type AboutStat = {
    /**
     * Label
     */
    label: string;
    /**
     * Value
     */
    value: string;
};

/**
 * AddressCreate
 */
export type AddressCreate = {
    /**
     * Line1
     */
    line1: string;
    /**
     * Line2
     */
    line2?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Country
     */
    country?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * BannerSection
 */
export type BannerSection = {
    /**
     * Label
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Primarybtntext
     */
    primaryBtnText: string;
    /**
     * Primarybtnlink
     */
    primaryBtnLink?: string;
    /**
     * Ghostbtntext
     */
    ghostBtnText: string;
    /**
     * Ghostbtnlink
     */
    ghostBtnLink?: string;
};

/**
 * BearerResponse
 */
export type BearerResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * Body_auth-reset:forgot_password
 */
export type BodyAuthResetForgotPassword = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_auth-reset:reset_password
 */
export type BodyAuthResetResetPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Body_auth-verify:request-token
 */
export type BodyAuthVerifyRequestToken = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_auth-verify:verify
 */
export type BodyAuthVerifyVerify = {
    /**
     * Token
     */
    token: string;
};

/**
 * CartItemCreate
 */
export type CartItemCreate = {
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Course Id
     */
    course_id?: number | null;
    /**
     * Quantity
     */
    quantity?: number;
};

/**
 * CartItemRead
 */
export type CartItemRead = {
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Course Id
     */
    course_id?: number | null;
    /**
     * Quantity
     */
    quantity?: number;
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: string;
    product?: ProductRead | null;
    course?: CourseRead | null;
};

/**
 * CartItemUpdate
 */
export type CartItemUpdate = {
    /**
     * Quantity
     */
    quantity: number;
};

/**
 * CommunitySection
 */
export type CommunitySection = {
    /**
     * Label
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Items
     */
    items?: Array<TestimonialItem>;
};

/**
 * CourseRead
 */
export type CourseRead = {
    /**
     * Title
     */
    title: string;
    /**
     * Instructor
     */
    instructor: string;
    /**
     * Duration
     */
    duration?: string | null;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Price
     */
    price: number;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Rating
     */
    rating: number;
    /**
     * Students Count
     */
    students_count: number;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
    /**
     * Detail
     */
    detail: string | {
        [key: string]: string;
    };
};

/**
 * FaqItem
 */
export type FaqItem = {
    /**
     * Question
     */
    question: string;
    /**
     * Answer
     */
    answer: string;
};

/**
 * FaqSection
 */
export type FaqSection = {
    /**
     * Label
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Items
     */
    items?: Array<FaqItem>;
};

/**
 * FeaturedSection
 */
export type FeaturedSection = {
    /**
     * Label
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Items
     *
     * IDs of featured entities
     */
    items?: Array<number>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HeroSection
 */
export type HeroSection = {
    /**
     * Title
     */
    title: string;
    /**
     * Subtitle
     */
    subtitle: string;
    /**
     * Primarybtntext
     */
    primaryBtnText: string;
    /**
     * Primarybtnlink
     */
    primaryBtnLink?: string;
    /**
     * Ghostbtntext
     */
    ghostBtnText: string;
    /**
     * Ghostbtnlink
     */
    ghostBtnLink?: string;
    /**
     * Mediatype
     */
    mediaType?: 'image' | 'video';
    /**
     * Mediaurl
     */
    mediaUrl: string;
    /**
     * Stats
     */
    stats?: Array<HeroStat>;
};

/**
 * HeroStat
 */
export type HeroStat = {
    /**
     * Label
     */
    label: string;
    /**
     * Value
     */
    value: string;
};

/**
 * HomePageConfig
 */
export type HomePageConfig = {
    hero: HeroSection;
    featuredPaintings: FeaturedSection;
    featuredCourses: FeaturedSection;
    collection: FeaturedSection;
    bestSellers: FeaturedSection;
    about: AboutSection;
    videoCta: VideoCtaSection;
    faq: FaqSection;
    community: CommunitySection;
    banner: BannerSection;
};

/**
 * MetaModel
 */
export type MetaModel = {
    /**
     * Timestamp
     */
    timestamp?: string;
    /**
     * Error Code
     */
    error_code?: string | null;
};

/**
 * ProductRead
 */
export type ProductRead = {
    /**
     * Title
     */
    title: string;
    /**
     * Artist
     */
    artist: string;
    /**
     * Price
     */
    price: number;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Stock Quantity
     */
    stock_quantity?: number;
    /**
     * Id
     */
    id: number;
};

/**
 * ResponseModel
 *
 * Standard API response used across the app.
 *
 * Fields kept for backwards compatibility:
 * - status: HTTP status code (int)
 * - success: bool (kept to avoid breaking callers that read it)
 * - message, data, meta
 */
export type ResponseModel = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: unknown | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[AddressRead]
 */
export type ResponseModelAddressRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    data?: AppSchemasAddressAddressRead | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[Any]
 */
export type ResponseModelAny = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: unknown;
    meta?: MetaModel;
};

/**
 * ResponseModel[CartItemRead]
 */
export type ResponseModelCartItemRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    data?: CartItemRead | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[CourseRead]
 */
export type ResponseModelCourseRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    data?: CourseRead | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[HomePageConfig]
 */
export type ResponseModelHomePageConfig = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    data?: HomePageConfig | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[ProductRead]
 */
export type ResponseModelProductRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    data?: ProductRead | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[ReviewRead]
 */
export type ResponseModelReviewRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    data?: ReviewRead | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[UserRead]
 */
export type ResponseModelUserRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    data?: UserRead | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[WishlistRead]
 */
export type ResponseModelWishlistRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    data?: WishlistRead | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[dict]
 */
export type ResponseModelDict = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    } | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[list[AddressRead]]
 */
export type ResponseModelListAddressRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<AppSchemasAddressAddressRead> | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[list[CartItemRead]]
 */
export type ResponseModelListCartItemRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<CartItemRead> | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[list[CourseRead]]
 */
export type ResponseModelListCourseRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<CourseRead> | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[list[ProductRead]]
 */
export type ResponseModelListProductRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ProductRead> | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[list[ReviewReadPublic]]
 */
export type ResponseModelListReviewReadPublic = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ReviewReadPublic> | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[list[ReviewRead]]
 */
export type ResponseModelListReviewRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ReviewRead> | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[list[UserRead]]
 */
export type ResponseModelListUserRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<UserRead> | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[list[WishlistRead]]
 */
export type ResponseModelListWishlistRead = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<WishlistRead> | null;
    meta?: MetaModel;
};

/**
 * ResponseModel[list[dict]]
 */
export type ResponseModelListDict = {
    /**
     * Status
     */
    status?: number;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<{
        [key: string]: unknown;
    }> | null;
    meta?: MetaModel;
};

/**
 * ReviewCreate
 */
export type ReviewCreate = {
    type: ReviewType;
    /**
     * Entity Id
     */
    entity_id?: number | null;
    /**
     * Rating
     */
    rating: number;
    /**
     * Text
     */
    text: string;
};

/**
 * ReviewRead
 */
export type ReviewRead = {
    type: ReviewType;
    /**
     * Entity Id
     */
    entity_id?: number | null;
    /**
     * Rating
     */
    rating: number;
    /**
     * Text
     */
    text: string;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    status: ReviewStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ReviewReadPublic
 *
 * Public version without sensitive info
 */
export type ReviewReadPublic = {
    type: ReviewType;
    /**
     * Entity Id
     */
    entity_id?: number | null;
    /**
     * Rating
     */
    rating: number;
    /**
     * Text
     */
    text: string;
    /**
     * Id
     */
    id: string;
    status: ReviewStatus;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ReviewStatus
 */
export type ReviewStatus = 'pending' | 'approved' | 'blocked';

/**
 * ReviewType
 */
export type ReviewType = 'site' | 'product' | 'painting';

/**
 * ReviewUpdate
 */
export type ReviewUpdate = {
    status?: ReviewStatus | null;
    /**
     * Rating
     */
    rating?: number | null;
    /**
     * Text
     */
    text?: string | null;
};

/**
 * TestimonialItem
 */
export type TestimonialItem = {
    /**
     * Name
     */
    name: string;
    /**
     * Role
     */
    role: string;
    /**
     * Text
     */
    text: string;
    /**
     * Rating
     */
    rating?: number;
    /**
     * Avatar
     */
    avatar: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Role
     */
    role?: string | null;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Is Verified
     */
    is_verified?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Role
     */
    role?: string | null;
    /**
     * Addresses
     */
    addresses?: Array<AppSchemasUserAddressRead> | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Password
     */
    password?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Role
     */
    role?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VideoCtaSection
 */
export type VideoCtaSection = {
    /**
     * Label
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Bgimage
     */
    bgImage: string;
    /**
     * Videourl
     */
    videoUrl: string;
};

/**
 * WishlistCreate
 */
export type WishlistCreate = {
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Course Id
     */
    course_id?: number | null;
};

/**
 * WishlistRead
 */
export type WishlistRead = {
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Course Id
     */
    course_id?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: string;
    product?: ProductRead | null;
    course?: CourseRead | null;
};

/**
 * AddressRead
 */
export type AppSchemasAddressAddressRead = {
    /**
     * Line1
     */
    line1: string;
    /**
     * Line2
     */
    line2?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Country
     */
    country?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Is Default
     */
    is_default?: boolean;
    /**
     * Id
     */
    id: number;
};

/**
 * AddressRead
 */
export type AppSchemasUserAddressRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Line1
     */
    line1: string;
    /**
     * Line2
     */
    line2?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Country
     */
    country?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * Body_auth-auth:jwt.login
 */
export type Login = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ApiMeta
 */
export type ApiMeta = {
    timestamp: string;
    error_code?: string;
};

/**
 * ApiResponse
 */
export type ApiResponse = {
    status: number;
    message: string;
    data?: unknown;
    meta: ApiMeta;
};

export type AuthJwtLoginData = {
    body: Login;
    path?: never;
    query?: never;
    url: '/api/auth/jwt/login';
};

export type AuthJwtLoginErrors = {
    /**
     * Bad Request
     */
    400: ApiResponse & {
        data?: ErrorModel;
    };
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type AuthJwtLoginError = AuthJwtLoginErrors[keyof AuthJwtLoginErrors];

export type AuthJwtLoginResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: BearerResponse;
    };
};

export type AuthJwtLoginResponse = AuthJwtLoginResponses[keyof AuthJwtLoginResponses];

export type AuthJwtLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/jwt/logout';
};

export type AuthJwtLogoutErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type AuthJwtLogoutResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: unknown;
    };
};

export type AuthJwtLogoutResponse = AuthJwtLogoutResponses[keyof AuthJwtLogoutResponses];

export type RegisterRegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterRegisterErrors = {
    /**
     * Bad Request
     */
    400: ApiResponse & {
        data?: ErrorModel;
    };
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type RegisterRegisterError = RegisterRegisterErrors[keyof RegisterRegisterErrors];

export type RegisterRegisterResponses = {
    /**
     * Successful Response
     */
    201: ApiResponse & {
        data?: UserRead;
    };
};

export type RegisterRegisterResponse = RegisterRegisterResponses[keyof RegisterRegisterResponses];

export type ResetForgotPasswordData = {
    body: BodyAuthResetForgotPassword;
    path?: never;
    query?: never;
    url: '/api/auth/forgot-password';
};

export type ResetForgotPasswordErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type ResetForgotPasswordError = ResetForgotPasswordErrors[keyof ResetForgotPasswordErrors];

export type ResetForgotPasswordResponses = {
    /**
     * Successful Response
     */
    202: ApiResponse & {
        data?: unknown;
    };
};

export type ResetForgotPasswordResponse = ResetForgotPasswordResponses[keyof ResetForgotPasswordResponses];

export type ResetResetPasswordData = {
    body: BodyAuthResetResetPassword;
    path?: never;
    query?: never;
    url: '/api/auth/reset-password';
};

export type ResetResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: ApiResponse & {
        data?: ErrorModel;
    };
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type ResetResetPasswordError = ResetResetPasswordErrors[keyof ResetResetPasswordErrors];

export type ResetResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: unknown;
    };
};

export type ResetResetPasswordResponse = ResetResetPasswordResponses[keyof ResetResetPasswordResponses];

export type VerifyRequestTokenData = {
    body: BodyAuthVerifyRequestToken;
    path?: never;
    query?: never;
    url: '/api/auth/request-verify-token';
};

export type VerifyRequestTokenErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type VerifyRequestTokenError = VerifyRequestTokenErrors[keyof VerifyRequestTokenErrors];

export type VerifyRequestTokenResponses = {
    /**
     * Successful Response
     */
    202: ApiResponse & {
        data?: unknown;
    };
};

export type VerifyRequestTokenResponse = VerifyRequestTokenResponses[keyof VerifyRequestTokenResponses];

export type VerifyVerifyData = {
    body: BodyAuthVerifyVerify;
    path?: never;
    query?: never;
    url: '/api/auth/verify';
};

export type VerifyVerifyErrors = {
    /**
     * Bad Request
     */
    400: ApiResponse & {
        data?: ErrorModel;
    };
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type VerifyVerifyError = VerifyVerifyErrors[keyof VerifyVerifyErrors];

export type VerifyVerifyResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: UserRead;
    };
};

export type VerifyVerifyResponse = VerifyVerifyResponses[keyof VerifyVerifyResponses];

export type UsersCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UsersCurrentUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type UsersCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: UserRead;
    };
};

export type UsersCurrentUserResponse = UsersCurrentUserResponses[keyof UsersCurrentUserResponses];

export type UsersPatchCurrentUserData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UsersPatchCurrentUserErrors = {
    /**
     * Bad Request
     */
    400: ApiResponse & {
        data?: ErrorModel;
    };
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type UsersPatchCurrentUserError = UsersPatchCurrentUserErrors[keyof UsersPatchCurrentUserErrors];

export type UsersPatchCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: UserRead;
    };
};

export type UsersPatchCurrentUserResponse = UsersPatchCurrentUserResponses[keyof UsersPatchCurrentUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UsersUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type UsersUserError = UsersUserErrors[keyof UsersUserErrors];

export type UsersUserResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: UserRead;
    };
};

export type UsersUserResponse = UsersUserResponses[keyof UsersUserResponses];

export type UsersPatchUserData = {
    body: UserUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UsersPatchUserErrors = {
    /**
     * Bad Request
     */
    400: ApiResponse & {
        data?: ErrorModel;
    };
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type UsersPatchUserError = UsersPatchUserErrors[keyof UsersPatchUserErrors];

export type UsersPatchUserResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: UserRead;
    };
};

export type UsersPatchUserResponse = UsersPatchUserResponses[keyof UsersPatchUserResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelAny;
    };
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type HealthCheckDetailedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/detailed';
};

export type HealthCheckDetailedResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelAny;
    };
};

export type HealthCheckDetailedResponse = HealthCheckDetailedResponses[keyof HealthCheckDetailedResponses];

export type ReadOwnProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profiles/me';
};

export type ReadOwnProfileResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelUserRead;
    };
};

export type ReadOwnProfileResponse = ReadOwnProfileResponses[keyof ReadOwnProfileResponses];

export type ListProfilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
    };
    url: '/api/profiles';
};

export type ListProfilesErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type ListProfilesError = ListProfilesErrors[keyof ListProfilesErrors];

export type ListProfilesResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelListUserRead;
    };
};

export type ListProfilesResponse = ListProfilesResponses[keyof ListProfilesResponses];

export type ListAddressesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/addresses';
};

export type ListAddressesResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelListAddressRead;
    };
};

export type ListAddressesResponse = ListAddressesResponses[keyof ListAddressesResponses];

export type CreateAddressData = {
    body: AddressCreate;
    path?: never;
    query?: never;
    url: '/api/addresses';
};

export type CreateAddressErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type CreateAddressError = CreateAddressErrors[keyof CreateAddressErrors];

export type CreateAddressResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelAddressRead;
    };
};

export type CreateAddressResponse = CreateAddressResponses[keyof CreateAddressResponses];

export type DeleteAddressData = {
    body?: never;
    path: {
        /**
         * Address Id
         */
        address_id: number;
    };
    query?: never;
    url: '/api/addresses/{address_id}';
};

export type DeleteAddressErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type DeleteAddressError = DeleteAddressErrors[keyof DeleteAddressErrors];

export type DeleteAddressResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelDict;
    };
};

export type DeleteAddressResponse = DeleteAddressResponses[keyof DeleteAddressResponses];

export type ListReviewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Review Type
         */
        review_type?: ReviewType | null;
        /**
         * Entity Id
         */
        entity_id?: number | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/reviews';
};

export type ListReviewsErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type ListReviewsError = ListReviewsErrors[keyof ListReviewsErrors];

export type ListReviewsResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelListReviewReadPublic;
    };
};

export type ListReviewsResponse = ListReviewsResponses[keyof ListReviewsResponses];

export type CreateReviewData = {
    body: ReviewCreate;
    path?: never;
    query?: never;
    url: '/api/reviews';
};

export type CreateReviewErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type CreateReviewError = CreateReviewErrors[keyof CreateReviewErrors];

export type CreateReviewResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelReviewRead;
    };
};

export type CreateReviewResponse = CreateReviewResponses[keyof CreateReviewResponses];

export type GetMyReviewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/reviews/user/my-reviews';
};

export type GetMyReviewsResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelListReviewRead;
    };
};

export type GetMyReviewsResponse = GetMyReviewsResponses[keyof GetMyReviewsResponses];

export type AdminStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/stats';
};

export type AdminStatsResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: unknown;
    };
};

export type AdminStatsResponse = AdminStatsResponses[keyof AdminStatsResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/users/';
};

export type ListUsersResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelListDict;
    };
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/admin/users/{user_id}';
};

export type GetUserErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelDict;
    };
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type ListCoursesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/courses/';
};

export type ListCoursesResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: unknown;
    };
};

export type ListCoursesResponse = ListCoursesResponses[keyof ListCoursesResponses];

export type GetCourseData = {
    body?: never;
    path: {
        /**
         * Course Id
         */
        course_id: string;
    };
    query?: never;
    url: '/api/admin/courses/{course_id}';
};

export type GetCourseErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type GetCourseError = GetCourseErrors[keyof GetCourseErrors];

export type GetCourseResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: unknown;
    };
};

export type GetCourseResponse = GetCourseResponses[keyof GetCourseResponses];

export type ListProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/products/';
};

export type ListProductsResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: unknown;
    };
};

export type ListProductsResponse = ListProductsResponses[keyof ListProductsResponses];

export type GetProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/admin/products/{product_id}';
};

export type GetProductErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type GetProductError = GetProductErrors[keyof GetProductErrors];

export type GetProductResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: unknown;
    };
};

export type GetProductResponse = GetProductResponses[keyof GetProductResponses];

export type OverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/dashboard/overview';
};

export type OverviewResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: unknown;
    };
};

export type OverviewResponse = OverviewResponses[keyof OverviewResponses];

export type GetHomePageSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/config/home';
};

export type GetHomePageSettingsResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelHomePageConfig;
    };
};

export type GetHomePageSettingsResponse = GetHomePageSettingsResponses[keyof GetHomePageSettingsResponses];

export type UpdateHomePageSettingsData = {
    body: HomePageConfig;
    path?: never;
    query?: never;
    url: '/api/admin/config/home';
};

export type UpdateHomePageSettingsErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type UpdateHomePageSettingsError = UpdateHomePageSettingsErrors[keyof UpdateHomePageSettingsErrors];

export type UpdateHomePageSettingsResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelHomePageConfig;
    };
};

export type UpdateHomePageSettingsResponse = UpdateHomePageSettingsResponses[keyof UpdateHomePageSettingsResponses];

export type ListAllReviewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Review Type
         */
        review_type?: ReviewType | null;
        /**
         * Entity Id
         */
        entity_id?: number | null;
        /**
         * Status
         */
        status?: ReviewStatus | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/admin/reviews';
};

export type ListAllReviewsErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type ListAllReviewsError = ListAllReviewsErrors[keyof ListAllReviewsErrors];

export type ListAllReviewsResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelListReviewRead;
    };
};

export type ListAllReviewsResponse = ListAllReviewsResponses[keyof ListAllReviewsResponses];

export type DeleteReviewData = {
    body?: never;
    path: {
        /**
         * Review Id
         */
        review_id: string;
    };
    query?: never;
    url: '/api/admin/reviews/{review_id}';
};

export type DeleteReviewErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type DeleteReviewError = DeleteReviewErrors[keyof DeleteReviewErrors];

export type DeleteReviewResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelDict;
    };
};

export type DeleteReviewResponse = DeleteReviewResponses[keyof DeleteReviewResponses];

export type GetReviewDetailData = {
    body?: never;
    path: {
        /**
         * Review Id
         */
        review_id: string;
    };
    query?: never;
    url: '/api/admin/reviews/{review_id}';
};

export type GetReviewDetailErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type GetReviewDetailError = GetReviewDetailErrors[keyof GetReviewDetailErrors];

export type GetReviewDetailResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelReviewRead;
    };
};

export type GetReviewDetailResponse = GetReviewDetailResponses[keyof GetReviewDetailResponses];

export type UpdateReviewData = {
    body: ReviewUpdate;
    path: {
        /**
         * Review Id
         */
        review_id: string;
    };
    query?: never;
    url: '/api/admin/reviews/{review_id}';
};

export type UpdateReviewErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type UpdateReviewError = UpdateReviewErrors[keyof UpdateReviewErrors];

export type UpdateReviewResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelReviewRead;
    };
};

export type UpdateReviewResponse = UpdateReviewResponses[keyof UpdateReviewResponses];

export type ListCourses2Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/courses';
};

export type ListCourses2Errors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type ListCourses2Error = ListCourses2Errors[keyof ListCourses2Errors];

export type ListCourses2Responses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelListCourseRead;
    };
};

export type ListCourses2Response = ListCourses2Responses[keyof ListCourses2Responses];

export type GetCourse2Data = {
    body?: never;
    path: {
        /**
         * Course Id
         */
        course_id: number;
    };
    query?: never;
    url: '/api/courses/{course_id}';
};

export type GetCourse2Errors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type GetCourse2Error = GetCourse2Errors[keyof GetCourse2Errors];

export type GetCourse2Responses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelCourseRead;
    };
};

export type GetCourse2Response = GetCourse2Responses[keyof GetCourse2Responses];

export type ListProducts2Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/products';
};

export type ListProducts2Errors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type ListProducts2Error = ListProducts2Errors[keyof ListProducts2Errors];

export type ListProducts2Responses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelListProductRead;
    };
};

export type ListProducts2Response = ListProducts2Responses[keyof ListProducts2Responses];

export type GetProduct2Data = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/api/products/{product_id}';
};

export type GetProduct2Errors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type GetProduct2Error = GetProduct2Errors[keyof GetProduct2Errors];

export type GetProduct2Responses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelProductRead;
    };
};

export type GetProduct2Response = GetProduct2Responses[keyof GetProduct2Responses];

export type GetMyCartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/cart';
};

export type GetMyCartResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelListCartItemRead;
    };
};

export type GetMyCartResponse = GetMyCartResponses[keyof GetMyCartResponses];

export type AddToCartData = {
    body: CartItemCreate;
    path?: never;
    query?: never;
    url: '/api/cart';
};

export type AddToCartErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type AddToCartError = AddToCartErrors[keyof AddToCartErrors];

export type AddToCartResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelCartItemRead;
    };
};

export type AddToCartResponse = AddToCartResponses[keyof AddToCartResponses];

export type RemoveFromCartData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/api/cart/{item_id}';
};

export type RemoveFromCartErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type RemoveFromCartError = RemoveFromCartErrors[keyof RemoveFromCartErrors];

export type RemoveFromCartResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModel;
    };
};

export type RemoveFromCartResponse = RemoveFromCartResponses[keyof RemoveFromCartResponses];

export type UpdateCartItemData = {
    body: CartItemUpdate;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/api/cart/{item_id}';
};

export type UpdateCartItemErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type UpdateCartItemError = UpdateCartItemErrors[keyof UpdateCartItemErrors];

export type UpdateCartItemResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelCartItemRead;
    };
};

export type UpdateCartItemResponse = UpdateCartItemResponses[keyof UpdateCartItemResponses];

export type GetMyWishlistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/wishlist';
};

export type GetMyWishlistResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelListWishlistRead;
    };
};

export type GetMyWishlistResponse = GetMyWishlistResponses[keyof GetMyWishlistResponses];

export type AddToWishlistData = {
    body: WishlistCreate;
    path?: never;
    query?: never;
    url: '/api/wishlist';
};

export type AddToWishlistErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type AddToWishlistError = AddToWishlistErrors[keyof AddToWishlistErrors];

export type AddToWishlistResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModelWishlistRead;
    };
};

export type AddToWishlistResponse = AddToWishlistResponses[keyof AddToWishlistResponses];

export type RemoveFromWishlistData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/api/wishlist/{item_id}';
};

export type RemoveFromWishlistErrors = {
    /**
     * Validation Error
     */
    422: ApiResponse & {
        data?: HttpValidationError;
    };
};

export type RemoveFromWishlistError = RemoveFromWishlistErrors[keyof RemoveFromWishlistErrors];

export type RemoveFromWishlistResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse & {
        data?: ResponseModel;
    };
};

export type RemoveFromWishlistResponse = RemoveFromWishlistResponses[keyof RemoveFromWishlistResponses];
